name: بناء أحمد شاقي APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04      # تأكيد الإصدار القديم
    steps:
      - name: تحميل الكود
        uses: actions/checkout@v4

      - name: تثبيت حزم النظام الأساسية
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            python3-pip \
            python3-dev \
            python3-setuptools \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo-dev \
            cmake \
            libffi-dev \
            libssl-dev \
            libltdl-dev

      - name: تثبيت Buildozer
        run: pip3 install --user buildozer

      - name: بناء APK
        env:
          BUILDOZER_ALLOW_ROOT: 1
        run: |
          export PATH=$PATH:/home/runner/.local/bin
          yes | buildozer android debug

      - name: رفع APK
        uses: actions/upload-artifact@v4
        with:
          name: Ahmed-Shaqi-APK
          path: bin/*.apk
